#声明相关依赖库,  该文件中的都为编译时相关处理
[libraries]


# gradle 插件
kotlin_gradle_plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
butterknife_compiler_gradle_plugin = { module = "com.jakewharton:butterknife-gradle-plugin", version.ref = "butterKnife" }


# 注解处理器
glide_compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
butterknife_compiler = { module = "com.jakewharton:butterknife-compiler", version.ref = "butterKnife" }