# 声明相关库版本号
[versions]

# Android 环境相关
compileSdk = "32"
minSdk = "23"
targetSdk = "29"

androidGradlePlugin = "7.3.1"

# Junit 测试相关
junit = "4.+"
testExtJunit = "1.1.3"
testEspressoCore = "3.4.0"


kotlin = "1.8.0"
kotlinCoroutines = "1.4.2"
compose = "1.3.1"
coreKtx = "1.7.0"
lifecycle = "2.4.0"
material = "1.7.0"
material3 = "1.0.1"

appcompat = "1.4.0"
constraintLayout = "2.1.4"
activity = "1.4.0"
fragment = "1.4.0"
securityCrypto = "1.0.0"
recyclerview = "1.2.1"
dataBinding = "7.2.2"
cameraX = "1.2.0"
palette = "1.0.0"
startup = "1.1.1"

navVersion = "2.5.3"

xlog = "1.10.1"
androidAutoSize = "v1.2.1"

retrofit = "2.9.0"
okhttp = "4.2.2"
easyHttp = "11.2"
immersionBar = "3.2.2"
eventBus = "3.3.1"
rxJava3 = "3.1.3"
rxAndroid = "3.0.0"
fancyToast = "2.0.1"
glide = "4.12.0"
permissionX = "1.7.1"
gson = "2.8.9"
fastJson = "1.1.72.android"
butterKnife = "10.2.1"
brvah = "3.0.7"
xPopup = "2.9.16"
zxingLite = "2.1.1"
utilCodeX = "1.31.1"
shortcutBadger = "1.1.22"
photoView = "latest.release"
banner = "2.2.2"
jsBridge = "1.0.4"
smartRefreshLayout = "2.0.5"
pictureSelector = "v3.0.6"
androidFilePicker = "0.75"
shapeView = "8.5"
calendarView = "3.7.1"
flowLayout = "1.1.2"
camera = "1.1.9"
verificationCodeInputView = "1.0.2"
gsyVideoPlayer = "v8.2.0-release-jitpack"
weiXinOpenSdk = "+"
tbsSdk = "44181"
tencentCos = "5.9.+"
updateAppUtilsx = "2.3.0"
lottie = "5.0.3"
waveSideBar = "1.3"
sideBar = "1.0.0"
shadow = "2.3.0"